permalink: /posts/:title/
name: Justin Cauchon
url: https://cauchon.net/
title: Justin Cauchon's Homepage & Projects
description: Justin Cauchon's website
future: true
twitter: Cauchon
gravatar_url: https://s.gravatar.com/avatar/8121bf21e10ab27ff5c8334e96097d13?s=80
google_analytics_tracking_id: UA-121235266-2
